GRANT EXECUTE ON DB.DBA.SPARUL_CLEAR TO "SPARQL";
GRANT EXECUTE ON DB.DBA.SPARUL_LOAD TO "SPARQL";
GRANT EXECUTE ON DB.DBA.SPARUL_INSERT TO "SPARQL";
GRANT EXECUTE ON DB.DBA.SPARUL_DELETE TO "SPARQL";
GRANT EXECUTE ON DB.DBA.SPARQL_DELETE_DICT_CONTENT TO "SPARQL";