<template>
  <div class="shacl-violation-card">
    <!-- Card Header -->
    <div class="card-header">
      <div class="flex items-center gap-3">
        <!-- Constraint Icon -->
        <div class="constraint-icon">
          <component :is="getConstraintIcon()" class="w-6 h-6" />
        </div>

        <!-- Title -->
        <div class="flex-1">
          <h3 class="card-title">
            {{ getConstraintTitle() }}
          </h3>
          <p class="card-subtitle" v-if="getConstraintSubtitle()">
            {{ getConstraintSubtitle() }}
          </p>
        </div>

        <!-- Status Badge -->
        <div class="status-badge" :class="getStatusClass()">
          {{ getStatusText() }}
        </div>
      </div>
    </div>

    <!-- Violation Overview Panel (Centered, Open) -->
    <div class="violation-overview-panel" v-if="context?.ai_explanation || context">
      <div class="violation-overview-content">
        <div class="overview-header">
          <div class="overview-icon">
            <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z"></path>
            </svg>
          </div>
          <h3 class="overview-title">Violation Overview</h3>
        <div class="overview-info-section">
          <!-- AI Processing Spinner -->
          <div v-if="isProcessingAI" class="ai-processing-spinner" :title="aiProcessingTooltip">
            <svg class="animate-spin h-4 w-4" fill="none" viewBox="0 0 24 24">
              <circle class="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" stroke-width="4"></circle>
              <path class="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
            </svg>
          </div>
          <!-- Metadata Info Icon -->
          <div class="overview-info-trigger" @click="toggleMetadata" :title="metadataTooltip">
            <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z"></path>
            </svg>
          </div>
        </div>
        </div>

        <!-- Overview Content -->
        <div class="overview-content-grid">
          <!-- Left Column: Basic Info -->
          <div class="overview-left">
            <div class="overview-property-row">
              <span class="overview-property-label">Property:</span>
              <span class="overview-property-value">{{ formatPropertyName(resultPath) }}</span>
            </div>
            <div class="overview-property-row">
              <span class="overview-property-label">Current Value:</span>
              <span class="overview-property-value">{{ formatValue(value) }}</span>
            </div>
          </div>

          <!-- Right Column: AI Explanation -->
          <div class="overview-right" v-if="context?.ai_explanation">
            <div class="overview-explanation">
              <h4 class="explanation-label">AI Explanation:</h4>
              <p class="explanation-text">{{ context.ai_explanation }}</p>
            </div>
          </div>
        </div>

        <!-- Metadata Modal (shown when info icon is clicked) -->
        <div v-if="showMetadata" class="metadata-overlay" @click="toggleMetadata">
          <div class="metadata-modal" @click.stop>
            <div class="modal-header">
              <h4 class="modal-title">Explanation Metadata</h4>
              <button @click="toggleMetadata" class="modal-close">
                <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12"></path>
                </svg>
              </button>
            </div>
            <div class="modal-content">
              <!-- Real metadata from backend -->
              <template v-if="context?.explanation_metadata">
                <div class="metadata-item">
                  <span class="metadata-label">Generated by:</span>
                  <span class="metadata-value">{{ context.explanation_metadata.generated_by || 'Unknown' }}</span>
                </div>
                <div class="metadata-item">
                  <span class="metadata-label">Model Version:</span>
                  <span class="metadata-value">{{ context.explanation_metadata.model_version || 'Unknown' }}</span>
                </div>
                <div class="metadata-item" v-if="context.explanation_metadata.generated_timestamp">
                  <span class="metadata-label">Generated on:</span>
                  <span class="metadata-value">{{ formatTimestamp(context.explanation_metadata.generated_timestamp) }}</span>
                </div>
                <div class="metadata-item">
                  <span class="metadata-label">Confidence:</span>
                  <span class="metadata-value">{{ context.explanation_metadata.confidence_level || 'Unknown' }}</span>
                </div>
                <div class="metadata-item" v-if="context.explanation_metadata.extraction_method">
                  <span class="metadata-label">Method:</span>
                  <span class="metadata-value">{{ context.explanation_metadata.extraction_method }}</span>
                </div>
                <div class="metadata-item" v-if="context.explanation_metadata.constraint_signature">
                  <span class="metadata-label">Constraint:</span>
                  <span class="metadata-value">{{ formatPropertyName(context.explanation_metadata.constraint_signature) }}</span>
                </div>
                <div class="metadata-item" v-if="context.explanation_metadata.source_vkg_graph">
                  <span class="metadata-label">Source:</span>
                  <span class="metadata-value">{{ context.explanation_metadata.source_vkg_graph }}</span>
                </div>
                <div class="metadata-item" v-if="context.explanation_metadata.explanation_signature">
                  <span class="metadata-label">Signature:</span>
                  <span class="metadata-value text-xs">{{ context.explanation_metadata.explanation_signature }}</span>
                </div>
                <div class="metadata-item" v-if="context.explanation_metadata.vkg_triples_count">
                  <span class="metadata-label">VKG Size:</span>
                  <span class="metadata-value">{{ context.explanation_metadata.vkg_triples_count }} triples</span>
                </div>
                <div class="metadata-item" v-if="context.explanation_metadata.created_date">
                  <span class="metadata-label">VKG Created:</span>
                  <span class="metadata-value">{{ formatTimestamp(context.explanation_metadata.created_date) }}</span>
                </div>
                <div class="metadata-item" v-if="context.explanation_metadata.modified_date">
                  <span class="metadata-label">VKG Modified:</span>
                  <span class="metadata-value">{{ formatTimestamp(context.explanation_metadata.modified_date) }}</span>
                </div>
                <div class="metadata-item" v-if="context.explanation_metadata.model_description">
                  <span class="metadata-label">Description:</span>
                  <span class="metadata-value text-xs">{{ context.explanation_metadata.model_description }}</span>
                </div>
              </template>

              <!-- Fallback for missing metadata -->
              <template v-else>
                <div class="metadata-item">
                  <span class="metadata-label">Generated by:</span>
                  <span class="metadata-value">SHACL-BI System</span>
                </div>
                <div class="metadata-item">
                  <span class="metadata-label">Generated on:</span>
                  <span class="metadata-value">{{ new Date().toLocaleDateString() }} at {{ new Date().toLocaleTimeString() }}</span>
                </div>
                <div class="metadata-item">
                  <span class="metadata-label">Violation ID:</span>
                  <span class="metadata-value">{{ formatPropertyName(focusNode) || 'Unknown' }}</span>
                </div>
                <div class="metadata-item">
                  <span class="metadata-label">Confidence:</span>
                  <span class="metadata-value">Medium (basic inference)</span>
                </div>
              </template>
            </div>
          </div>
        </div>
      </div>
    </div>

    <!-- Full Validation Details and Shape Details Cards (Side by Side) -->
    <div class="details-cards-container py-4">
      <!-- Full Validation Details Card -->
      <div class="detail-card validation-details">
        <div class="detail-card-header">
          <svg class="w-5 h-5 text-blue-500" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z"></path>
          </svg>
          <h4 class="detail-card-title">Full Violation Details</h4>
        </div>
        <div class="detail-card-content">
          <table class="details-table">
            <tbody>
              <tr v-if="focusNode">
                <td class="detail-label">Focus Node:</td>
                <td class="detail-value">{{ focusNode }}</td>
              </tr>
              <tr v-if="resultPath">
                <td class="detail-label">Result Path:</td>
                <td class="detail-value">{{ formatPropertyName(resultPath) }}</td>
              </tr>
              <tr v-if="value">
                <td class="detail-label">Value:</td>
                <td class="detail-value">{{ formatValue(value) }}</td>
              </tr>
              <tr v-if="message">
                <td class="detail-label">Message:</td>
                <td class="detail-value">{{ message }}</td>
              </tr>
              <tr v-if="context?.severity">
                <td class="detail-label">Severity:</td>
                <td class="detail-value">{{ context.severity }}</td>
              </tr>
              <tr v-if="constraintComponent">
                <td class="detail-label">Constraint Component:</td>
                <td class="detail-value">{{ formatPropertyName(constraintComponent) }}</td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>

      <!-- Shape Details Card -->
      <div class="detail-card shape-details">
        <div class="detail-card-header">
          <svg class="w-5 h-5 text-purple-500" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 11H5m14 0a2 2 0 012 2v6a2 2 0 01-2 2H5a2 2 0 01-2-2v-6a2 2 0 012-2m14 0V9a2 2 0 00-2-2M5 11V9a2 2 0 012-2m0 0V5a2 2 0 012-2h6a2 2 0 012 2v2M7 7h10"></path>
          </svg>
          <h4 class="detail-card-title">Shape Details</h4>
        </div>
        <div class="detail-card-content">
          <div v-if="context?.shape">
            <p><strong>Shape:</strong> {{ context.shape }}</p>
            <p><strong>Type:</strong> {{ context.shapeType || 'NodeShape' }}</p>
            <div v-if="context.shapeProperties && context.shapeProperties.length > 0">
              <p class="mt-3"><strong>Property Shapes:</strong></p>
              <ul class="property-list">
                <li v-for="(property, index) in context.shapeProperties" :key="index" class="property-item">
                  <span class="property-name">{{ formatPropertyName(property.path) }}:</span>
                  <span class="property-constraints">{{ formatConstraints(property.constraints) }}</span>
                </li>
              </ul>
            </div>
            <div v-if="context.targetClass">
              <p class="mt-3"><strong>Target Class:</strong> {{ formatPropertyName(context.targetClass) }}</p>
            </div>
          </div>
          <div v-else class="no-shape-data">
            No shape details available
          </div>
        </div>
      </div>
    </div>

  
    <!-- Constraint-Specific Content -->
    <div class="constraint-section">
      <slot name="constraint-content">
        <!-- Default content if no specific slot provided -->
        <div class="default-content">
          <p>{{ message }}</p>
        </div>
      </slot>
    </div>

    <!-- Action Section -->
      <div class="action-section">
        <slot name="action-content">
          <!-- Default action buttons -->
          <div class="default-actions">
            <button
              @click="rejectFix"
              class="action-btn secondary"
              :disabled="isLoading"
            >
              <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12"></path>
              </svg>
              Reject
            </button>

            <button
              @click="applyFix"
              class="action-btn primary"
              :disabled="!canApplyFix || isLoading"
            >
              <svg v-if="isLoading" class="w-4 h-4 animate-spin" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 4v5h.582m15.356 2A8.001 8.001 0 004.582 9m0 0H9m11 11v-5h-.581m0 0a8.003 8.003 0 01-15.357-2m15.357 2H15"></path>
              </svg>
              <svg v-else class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 13l4 4L19 7"></path>
              </svg>
              {{ isLoading ? 'Applying...' : 'Apply Fix' }}
            </button>
          </div>
        </slot>
      </div>

      <!-- Advanced Section (collapsible) -->
      <details class="advanced-section" v-if="showAdvanced">
        <summary class="advanced-summary">
          <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10.325 4.317c.426-1.756 2.924-1.756 3.35 0a1.724 1.724 0 002.573 1.066c1.543-.94 3.31.826 2.37 2.37a1.724 1.724 0 001.065 2.572c1.756.426 1.756 2.924 0 3.35a1.724 1.724 0 00-1.066 2.573c.94 1.543-.826 3.31-2.37 2.37a1.724 1.724 0 00-2.572 1.065c-.426 1.756-2.924 1.756-3.35 0a1.724 1.724 0 00-2.573-1.066c-1.543.94-3.31-.826-2.37-2.37a1.724 1.724 0 00-1.065-2.572c-1.756-.426-1.756-2.924 0-3.35a1.724 1.724 0 001.066-2.573c-.94-1.543.826-3.31 2.37-2.37.996.608 2.296.07 2.572-1.065z"></path>
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 12a3 3 0 11-6 0 3 3 0 016 0z"></path>
          </svg>
          Advanced Options
        </summary>
        <div class="advanced-content">
          <slot name="advanced-content">
            <!-- SPARQL Query Display -->
            <div class="sparql-section">
              <h4>SPARQL Query</h4>
              <pre class="sparql-query">{{ displayQuery }}</pre>
            </div>
          </slot>
        </div>
      </details>
  </div>
</template>

<script setup>
import { computed, ref, onMounted, onUnmounted } from 'vue'

const props = defineProps({
  // Basic violation information
  focusNode: String,
  resultPath: String,
  value: [String, Number],
  message: String,
  constraintComponent: String,

  // Constraint-specific context
  context: {
    type: Object,
    default: () => ({})
  },
  // Session ID for AI polling
  sessionId: {
    type: String,
    default: null
  },

  // Violation state
  isLoading: {
    type: Boolean,
    default: false
  },
  hasError: {
    type: Boolean,
    default: false
  },
  errorMessage: String,

  // Configuration
  showAdvanced: {
    type: Boolean,
    default: true
  },
  canApplyFix: {
    type: Boolean,
    default: true
  }
})

const emit = defineEmits(['reject-fix', 'apply-fix', 'explanation-updated'])

// State for metadata modal
const showMetadata = ref(false)

// State for AI processing
const isProcessingAI = ref(false)
const aiProcessingPollingInterval = ref(null)
const sessionId = ref(null)

// Computed properties for tooltips
const aiProcessingTooltip = computed(() => {
  return "An AI-based explanation for this violation is being generated..."
})

const metadataTooltip = computed(() => {
  if (isProcessingAI.value) {
    return "View explanation metadata (AI processing in progress...)"
  }
  return "View explanation metadata"
})
// Methods
const toggleMetadata = () => {
  showMetadata.value = !showMetadata.value
}

// Computed properties
const displayQuery = computed(() => {
  return props.context?.sparqlQuery || props.context?.proposed_repair?.query || 'No query available'
})

// Methods
const getConstraintIcon = () => {
  // Handle both full URIs (http://...#Component) and prefixed names (sh:Component)
  let constraintType = ''
  if (props.constraintComponent?.includes('#')) {
    constraintType = props.constraintComponent.split('#').pop() || ''
  } else {
    constraintType = props.constraintComponent || ''
  }

  // Remove prefix if present (e.g., "sh:" from "sh:InConstraintComponent")
  if (constraintType.includes(':')) {
    constraintType = constraintType.split(':').pop() || ''
  }

  // Map of constraint types to icon components
  const iconMap = {
    'ClassConstraintComponent': 'CheckCircleIcon',
    'DatatypeConstraintComponent': 'CodeBracketIcon',
    'NodeKindConstraintComponent': 'DocumentTextIcon',
    'MinCountConstraintComponent': 'PlusCircleIcon',
    'MaxCountConstraintComponent': 'MinusCircleIcon',
    'MinInclusiveConstraintComponent': 'ArrowTrendingUpIcon',
    'MaxInclusiveConstraintComponent': 'ArrowTrendingDownIcon',
    'MinLengthConstraintComponent': 'Bars3Icon',
    'MaxLengthConstraintComponent': 'Bars3BottomLeftIcon',
    'PatternConstraintComponent': 'FingerPrintIcon',
    'LanguageInConstraintComponent': 'LanguageIcon',
    'UniqueLangConstraintComponent': 'CheckBadgeIcon',
    'EqualsConstraintComponent': 'ArrowsPointingInIcon',
    'DisjointConstraintComponent': 'XMarkIcon',
    'LessThanConstraintComponent': 'ArrowLeftIcon',
    'LessThanOrEqualsConstraintComponent': 'ArrowSmallLeftIcon',
    'NotConstraintComponent': 'NoSymbolIcon',
    'AndConstraintComponent': 'LinkIcon',
    'OrConstraintComponent': 'LinkIcon',
    'XoneConstraintComponent': 'LinkIcon',
    'HasValueConstraintComponent': 'HashtagIcon',
    'InConstraintComponent': 'ListBulletIcon',
    'ClosedConstraintComponent': 'LockClosedIcon',
    'NodeConstraintComponent': 'CircleStackIcon',
    'QualifiedValueShapeConstraintComponent': 'CheckCircleIcon',
    'SPARQLConstraintComponent': 'CodeBracketIcon'
  }

  return iconMap[constraintType] || 'ExclamationTriangleIcon'
}

const getConstraintTitle = () => {
  // Handle both full URIs (http://...#Component) and prefixed names (sh:Component)
  let constraintType = ''
  if (props.constraintComponent?.includes('#')) {
    constraintType = props.constraintComponent.split('#').pop() || ''
  } else {
    constraintType = props.constraintComponent || ''
  }

  // Remove prefix if present (e.g., "sh:" from "sh:InConstraintComponent")
  if (constraintType.includes(':')) {
    constraintType = constraintType.split(':').pop() || ''
  }

  // Debug logging to see what we're getting
  console.log('🔍 Constraint Component:', props.constraintComponent)
  console.log('🔍 Extracted Type:', constraintType)

  const titleMap = {
    'ClassConstraintComponent': 'Wrong Type',
    'DatatypeConstraintComponent': 'Wrong Data Type',
    'NodeKindConstraintComponent': 'Wrong Node Kind',
    'MinCountConstraintComponent': 'Missing Required Values',
    'MaxCountConstraintComponent': 'Too Many Values',
    'MinInclusiveConstraintComponent': 'Value Too Small',
    'MaxInclusiveConstraintComponent': 'Value Too Large',
    'MinLengthConstraintComponent': 'Text Too Short',
    'MaxLengthConstraintComponent': 'Text Too Long',
    'PatternConstraintComponent': 'Invalid Format',
    'LanguageInConstraintComponent': 'Language Not Allowed',
    'UniqueLangConstraintComponent': 'Duplicate Language',
    'EqualsConstraintComponent': 'Values Not Equal',
    'DisjointConstraintComponent': 'Conflicting Values',
    'LessThanConstraintComponent': 'Value Not Less Than',
    'LessThanOrEqualsConstraintComponent': 'Value Not Less Or Equal',
    'NotConstraintComponent': 'Invalid Value',
    'AndConstraintComponent': 'Multiple Constraint Violations',
    'OrConstraintComponent': 'No Valid Options',
    'XoneConstraintComponent': 'Ambiguous Value',
    'HasValueConstraintComponent': 'Missing Required Value',
    'InConstraintComponent': 'Invalid Value',
    'ClosedConstraintComponent': 'Extra Properties',
    'NodeConstraintComponent': 'Invalid Resource',
    'QualifiedValueShapeConstraintComponent': 'Qualified Value Violation',
    'SPARQLConstraintComponent': 'Custom Rule Violation'
  }

  const selectedTitle = titleMap[constraintType] || 'Constraint Violation'
  console.log('🔍 Selected Title:', selectedTitle, 'for type:', constraintType)
  return selectedTitle
}

const getConstraintSubtitle = () => {
  // Provide specific subtitle based on constraint context
  if (props.context?.requiredClass) {
    return `Not an instance of: ${formatPropertyName(props.context.requiredClass)}`
  }
  if (props.context?.requiredDatatype) {
    return `Required type: ${props.context.requiredDatatype}`
  }
  if (props.context?.minValue !== undefined) {
    return `Minimum value: ${props.context.minValue}`
  }
  if (props.context?.maxValue !== undefined) {
    return `Maximum value: ${props.context.maxValue}`
  }
  if (props.context?.minLength !== undefined) {
    return `Minimum length: ${props.context.minLength} characters`
  }
  if (props.context?.maxLength !== undefined) {
    return `Maximum length: ${props.context.maxLength} characters`
  }
  if (props.context?.pattern) {
    return `Pattern: ${props.context.pattern}`
  }
  return null
}

const getStatusClass = () => {
  if (props.hasError) return 'status-error'
  if (props.isLoading) return 'status-loading'
  if (props.canApplyFix) return 'status-ready'
  return 'status-incomplete'
}

const getStatusText = () => {
  if (props.hasError) return 'Error'
  if (props.isLoading) return 'Processing'
  if (props.canApplyFix) return 'Ready'
  return 'Incomplete'
}

const formatPropertyName = (uri) => {
  if (!uri) return ''
  if (uri.includes(':') && !uri.startsWith('http')) {
    return uri
  }
  const parts = uri.split(/[#\/]/)
  return parts[parts.length - 1] || uri
}

const formatValue = (value) => {
  if (value === null || value === undefined) return 'null'
  if (typeof value === 'string') {
    // Check if it's a URI
    if (value.startsWith('http')) {
      return formatPropertyName(value)
    }
    return `"${value}"`
  }
  return String(value)
}

const formatConstraints = (constraints) => {
  if (!constraints || !Array.isArray(constraints)) return 'None'
  return constraints.map(c => formatPropertyName(c)).join(', ')
}

const formatTimestamp = (timestamp) => {
  if (!timestamp) return 'Unknown'
  try {
    const date = new Date(timestamp)
    return date.toLocaleDateString() + ' at ' + date.toLocaleTimeString()
  } catch (e) {
    return timestamp // Return original if parsing fails
  }
}

const rejectFix = () => {
  emit('reject-fix', {
    focusNode: props.focusNode,
    resultPath: props.resultPath,
    value: props.value,
    constraintComponent: props.constraintComponent
  })
}

const applyFix = () => {
  emit('apply-fix', {
    focusNode: props.focusNode,
    resultPath: props.resultPath,
    value: props.value,
    constraintComponent: props.constraintComponent,
    context: props.context
  })
}
// AI Processing Polling Methods
const startAIPolling = (currentSessionId) => {
  if (!currentSessionId) return
  
  sessionId.value = currentSessionId
  isProcessingAI.value = true
  
  // Clear any existing polling
  stopAIPolling()
  
  // Start polling every 3 seconds
  aiProcessingPollingInterval.value = setInterval(async () => {
    try {
      const response = await fetch(`/api/background-status/${sessionId.value}`)
      const data = await response.json()
      
      if (data.status === "completed") {
        // AI processing completed, refresh explanation data
        stopAIPolling()
        await refreshExplanation()
      } else if (data.status === "failed") {
        // AI processing failed
        stopAIPolling()
      }
    } catch (error) {
      console.error("Error checking AI processing status:", error)
    }
  }, 3000)
}

const stopAIPolling = () => {
  if (aiProcessingPollingInterval.value) {
    clearInterval(aiProcessingPollingInterval.value)
    aiProcessingPollingInterval.value = null
  }
  isProcessingAI.value = false
}

const refreshExplanation = async () => {
  try {
    if (!props.focusNode) return
    
    const session_id = localStorage.getItem("shacl_session_id")
    const response = await api.post("/api/explanation", {
      violation: {
        focus_node: props.focusNode,
        property_path: props.resultPath,
        constraint_id: props.constraintComponent,
        value: props.value,
        message: props.message
      },
      session_id
    })
    
    // Update context with new explanation data
    if (response.data) {
      // Emit event to parent to update context
      emit("explanation-updated", {
        focusNode: props.focusNode,
        resultPath: props.resultPath,
        constraintComponent: props.constraintComponent,
        explanationData: response.data
      })
    }
  } catch (error) {
    console.error("Error refreshing explanation:", error)
  }
}

// Lifecycle hooks
onMounted(() => {
  // Check if we should start polling based on initial context
  if (props.sessionId && (
      props.context?.explanation_metadata?.generated_by?.includes("AI") ||
      props.context?.explanation_metadata?.extraction_method === "ai_generation"
  )) {
    // This might be an AI-generated explanation that was enhanced
    const currentSessionId = props.sessionId
    if (currentSessionId) {
      startAIPolling(currentSessionId)
    }
  }
})

onUnmounted(() => {
  stopAIPolling()
})
</script>

<style scoped>
.shacl-violation-card {
  @apply bg-white border border-gray-200 rounded-lg shadow-sm overflow-hidden;
}

.card-header {
  @apply bg-gray-50 px-4 py-3 border-b border-gray-200;
}

.constraint-icon {
  @apply flex-shrink-0 text-amber-500;
}

.card-title {
  @apply text-lg font-semibold text-gray-800;
}

.card-subtitle {
  @apply text-sm text-gray-600 mt-1;
}

.status-badge {
  @apply px-2 py-1 text-xs font-medium rounded-full;
}

.status-ready {
  @apply bg-green-100 text-green-800;
}

.status-loading {
  @apply bg-blue-100 text-blue-800;
}

.status-error {
  @apply bg-red-100 text-red-800;
}

.status-incomplete {
  @apply bg-gray-100 text-gray-800;
}

.card-content {
  @apply p-4 space-y-6;
}

.context-section {
  @apply space-y-2;
}

.context-row {
  @apply flex items-center gap-2;
}

.context-label {
  @apply text-sm font-medium text-gray-500 min-w-20;
}

.context-value {
  @apply text-sm text-gray-800 font-mono bg-gray-50 px-2 py-1 rounded;
}

.constraint-section {
  @apply bg-blue-50 border border-blue-200 rounded-lg p-4;
}

.action-section {
  @apply pt-4 border-t border-gray-200;
}

.default-actions {
  @apply flex items-center gap-3 justify-end;
}

.action-btn {
  @apply inline-flex items-center gap-2 px-4 py-2 rounded-md text-sm font-medium transition-colors focus:outline-none focus:ring-2 focus:ring-offset-2;
}

.action-btn.primary {
  @apply bg-blue-600 text-white hover:bg-blue-700 focus:ring-blue-500 disabled:opacity-50 disabled:cursor-not-allowed;
}

.action-btn.secondary {
  @apply bg-white border border-gray-300 text-gray-700 hover:bg-gray-50 focus:ring-gray-500;
}

.advanced-section {
  @apply border-t border-gray-200 pt-4;
}

.advanced-summary {
  @apply flex items-center gap-2 cursor-pointer text-sm font-medium text-gray-700 hover:bg-gray-50 p-2 rounded -mx-2;
}

.advanced-content {
  @apply mt-3 space-y-4;
}

.sparql-section h4 {
  @apply text-sm font-medium text-gray-700 mb-2;
}

.sparql-query {
  @apply text-xs font-mono text-gray-700 whitespace-pre-wrap overflow-x-auto bg-gray-50 p-3 rounded border border-gray-200;
}

/* Violation Overview Panel */
.violation-overview-panel {
  @apply bg-gradient-to-r from-blue-50 to-purple-50 border border-blue-200 rounded-xl p-6 mx-auto w-full;
}

.violation-overview-content {
  @apply w-full max-w-4xl mx-auto;
}

.overview-header {
  @apply flex items-center justify-between mb-6;
}

.overview-icon {
  @apply text-blue-500;
}

.overview-title {
  @apply text-lg font-semibold text-gray-800 text-center flex-1;
}

.overview-info-trigger {
  @apply text-gray-400 hover:text-gray-600 cursor-pointer p-1 rounded hover:bg-white/50 transition-colors;
}

.overview-content-grid {
  @apply grid grid-cols-1 lg:grid-cols-2 gap-6;
}

.overview-left {
  @apply space-y-3;
}

.overview-property-row {
  @apply flex items-center gap-3;
}

.overview-property-label {
  @apply text-sm font-medium text-gray-600 min-w-20;
}

.overview-property-value {
  @apply text-sm text-gray-800 font-mono bg-white/60 px-3 py-1 rounded border border-blue-100;
}

.overview-right {
  @apply flex items-center;
}

.overview-explanation {
  @apply w-full;
}

.explanation-label {
  @apply text-sm font-semibold text-gray-700 mb-2;
}

.explanation-text {
  @apply text-sm text-gray-700 leading-relaxed bg-white/60 p-3 rounded-lg border border-blue-100;
}

/* Metadata Modal */
.metadata-overlay {
  @apply fixed inset-0 bg-black/50 flex items-center justify-center z-50;
}

.metadata-modal {
  @apply bg-white rounded-lg shadow-xl max-w-md w-full mx-4;
}

.modal-header {
  @apply flex items-center justify-between p-4 border-b border-gray-200;
}

.modal-title {
  @apply text-base font-semibold text-gray-800;
}

.modal-close {
  @apply text-gray-400 hover:text-gray-600 p-1 rounded hover:bg-gray-100 transition-colors;
}

.modal-content {
  @apply p-4 space-y-3;
}

.metadata-item {
  @apply flex justify-between items-center py-2 border-b border-gray-100 last:border-b-0;
}

.metadata-label {
  @apply text-sm font-medium text-gray-600;
}

.metadata-value {
  @apply text-sm text-gray-800 font-mono;
}
/* AI Processing Styles */
.overview-info-section {
  @apply flex items-center gap-2;
}

.ai-processing-spinner {
  @apply text-blue-500 animate-pulse;
}

.ai-processing-spinner svg {
  @apply h-4 w-4;
}

/* Details Cards Container */
.details-cards-container {
  @apply grid grid-cols-1 lg:grid-cols-2 gap-6;
}

/* Detail Cards */
.detail-card {
  @apply bg-white border border-gray-200 rounded-lg shadow-sm overflow-hidden;
}

.detail-card-header {
  @apply flex items-center gap-3 bg-gray-50 px-4 py-3 border-b border-gray-200;
}

.detail-card-title {
  @apply text-base font-semibold text-gray-800;
}

.detail-card-content {
  @apply p-4;
}

.details-table {
  @apply w-full;
}

.details-table td {
  @apply py-2 align-top;
}

.detail-label {
  @apply text-sm font-medium text-gray-600 pr-4 min-w-24;
}

.detail-value {
  @apply text-sm text-gray-800 font-mono bg-gray-50 px-2 py-1 rounded break-all;
}

/* Shape Details Specific */
.property-list {
  @apply list-none p-0 m-0 space-y-2;
}

.property-item {
  @apply bg-gray-50 p-2 rounded border border-gray-100;
}

.property-name {
  @apply font-medium text-gray-700 block mb-1;
}

.property-constraints {
  @apply text-sm text-gray-600 text-xs;
}

.no-shape-data {
  @apply text-gray-500 italic text-center py-4;
}

@keyframes spin {
  from { transform: rotate(0deg); }
  to { transform: rotate(360deg); }
}

.animate-spin {
  animation: spin 1s linear infinite;
}
</style>
